<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" retried="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="139" started-at="2020-12-24T20:32:48 IST" finished-at="2020-12-24T20:32:48 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="139" started-at="2020-12-24T20:32:48 IST" finished-at="2020-12-24T20:32:48 IST">
      <class name="com.mobile.testscripts.alertViews.SampleTest">
        <test-method status="SKIP" signature="retrycheck()[pri:0, instance:com.mobile.testscripts.alertViews.SampleTest@4f063c0a]" name="retrycheck" duration-ms="34" retried="true" started-at="2020-12-24T20:32:48 IST" finished-at="2020-12-24T20:32:48 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<1> but was:<2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<1> but was:<2>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at com.mobile.testscripts.alertViews.SampleTest.retrycheck(SampleTest.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- retrycheck -->
        <test-method status="PASS" signature="retrycheck()[pri:0, instance:com.mobile.testscripts.alertViews.SampleTest@4f063c0a]" name="retrycheck" duration-ms="1" started-at="2020-12-24T20:32:48 IST" finished-at="2020-12-24T20:32:48 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- retrycheck -->
      </class> <!-- com.mobile.testscripts.alertViews.SampleTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
